#!/bin/bash

cd 7

get_dofs="~/python_plotting/bash_template/runlists/dofs_0.txt"
get_constr="~/python_plotting/bash_template/runlists/constr_0.txt"

export get_dofs
export get_constr

~/uni/AlignmentDev_v17r0/build.x86_64-centos7-gcc9-opt/run ~/uni/AlignmentDev_v17r0/Alignment/Escher/scripts/gaudisplititer.py -n 10 -e 10000 --aligndb ~/python_plotting/bash_template/output/misalignment_runs/7/input_misalignment/ ~/uni/AlignmentDev_v17r0/Alignment/Escher/options/AlignFT_jobs.py